var searchData=
[
  ['vertexdof_141',['VertexDof',['../classVertexDof.html',1,'VertexDof'],['../classVertexDof.html#a68e11784ca8cf171f5c36b732ad9e0bc',1,'VertexDof::VertexDof()']]],
  ['virtualdof_142',['VirtualDof',['../classVirtualDof.html',1,'VirtualDof'],['../classVirtualDof.html#ac16c5ac6144bdce6229e87e5062b30d3',1,'VirtualDof::VirtualDof()']]],
  ['virtualdofscollection_143',['VirtualDofsCollection',['../classVirtualDofsCollection.html',1,'VirtualDofsCollection'],['../classVirtualDofsCollection.html#aa49b71503f6092dc629f398be73cdfce',1,'VirtualDofsCollection::VirtualDofsCollection()']]],
  ['virtualfaceprojections_144',['VirtualFaceProjections',['../classVirtualFaceProjections.html',1,'VirtualFaceProjections'],['../classVirtualFaceProjections.html#a40d7fc841c35678316b56db3f329cf52',1,'VirtualFaceProjections::VirtualFaceProjections()']]],
  ['virtualpolyhedronprojections_145',['VirtualPolyhedronProjections',['../classVirtualPolyhedronProjections.html',1,'VirtualPolyhedronProjections'],['../classVirtualPolyhedronProjections.html#a0a688f9292939840a53ca1e9820db083',1,'VirtualPolyhedronProjections::VirtualPolyhedronProjections(const real &amp;E, const real &amp;nu, const VirtualFaceProjections &amp;faceProjections, const LocalVirtualDofsCollection &amp;dofs, const Mesh&lt; Point3D, Edge3D, Polygon3D, Polyhedron&lt; Polygon3D &gt;&gt; &amp;mesh, const std::function&lt; real(real, real, real)&gt; &amp;funcx, const std::function&lt; real(real, real, real)&gt; &amp;funcy, const std::function&lt; real(real, real, real)&gt; &amp;funcz, const unsigned int &amp;order)'],['../classVirtualPolyhedronProjections.html#aa06587f29777757d0491198c1afacb44',1,'VirtualPolyhedronProjections::VirtualPolyhedronProjections(const Parameters &amp;parameters, const VirtualFaceProjections &amp;faceProjections, const LocalVirtualDofsCollection &amp;dofs, const Mesh&lt; Point3D, Edge3D, Polygon3D, Polyhedron&lt; Polygon3D &gt;&gt; &amp;mesh)']]],
  ['vtolocalid_146',['VToLocalId',['../classLocalVirtualDofs.html#abeb5f0190401205e85c9328e364f8b5e',1,'LocalVirtualDofs']]]
];
